server:
  host: "0.0.0.0"
  port: 50052

database:
  host: "localhost"
  port: 5433
  user: "card_db_user"
  password: "card_db_password"
  dbname: "card_db"
  ssl_mode: "disable"
  max_conns: 25
  min_conns: 5

jwt:
  secret_key: "superpupersecretkey"
  access_token_ttl: 15      # minutes
  refresh_token_ttl: 10080  # 7 days in minutes

