syntax = "proto3";

package card_service.v1;

import "google/type/date.proto";


option go_package = "github.com/mrevds/pizza-app/card-service/api/card-service_v1;card_service_v1";

service CardService {
    rpc AddCard(AddCardRequest) returns (AddCardResponse);
}


message Card {
    string card_number = 1;
    google.type.Date date_expire = 2;
    optional bool isActive = 3;
}

message AddCardRequest {
    Card cardData = 1;
    string cvv = 2;
}

message AddCardResponse {
    string card_id = 1;
    string message = 2;
    bool success = 3;
}