server:
  grpc_port: "50051"
  host: "0.0.0.0"

database:
  host: "user-db"
  port: "5432"
  user: "user_db_user"
  password: "user_db_password"
  dbname: "user_db"
  sslmode: "disable"
  max_conns: 25
  min_conns: 5

jwt:
  secret_key: "superpupersecretkey"
  access_token_duration: "15m"
  refresh_token_duration: "168h"

rate_limit:
  requests_per_second: 100

